theme: minima
title: Hazelnotes
Author: Hazel Branches
description: Hello and welcome to what will eventually be a collection of eclectic writings on communism, anarchism and my personal attempts to synthesises the two. It will also contain my extremely amateurish attempts at learning to program with ruby and through whys poignant guide to it. 
Everything written hear solely represents **me and not any organisations or groups I am a member of**/
Also occasionally I will write about maths, the hospitality industry and anything else which takes my fancy.

